import Head from "next/head";
import {
  Grid,
  GridItem,
  Box,
  HStack,
  Heading,
  Button,
  Container,
  Text,
} from "@chakra-ui/react";
import { Toaster } from "@/components/ui/toaster";
import { SpinnerDotted } from "spinners-react";
import Search from "../components/Search/Search";
import Results from "../components/Results/Results";
import AppDetails from "../components/Details/AppDetails";
import Insights from "@/components/Insights/Insights";
import Export from "@/components/Export/Export";

export default function Home() {
  return (
    <>
      <Head>
        <title>Smara</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box minH="100vh" bg="gray.50">
        <Toaster />

        <Container maxW="80rem" pt={8}>
          <Grid
            templateColumns="repeat(6,1fr)"
            justifyContent="center"
            gap={6}
            pb="12"
          >
            <GridItem colSpan={6}>
              <HStack>
                <Heading flex="1">SMARA Dashboard</Heading>
              </HStack>
            </GridItem>
            <Search />
            <Results />
            <Insights />
            <Export />
          </Grid>
        </Container>
      </Box>
    </>
  );
}
